### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by pedro-gutierrez** [distributeaid/toolbox#22]
**Is your feature request related to a problem? Please describe.**

At the moment, it is possible to create a category with name `Clothing` and then a second category named `clothing`.

**As a** group member
**I want to** have case insensitive names
**So that** so that I keep the aid taxonomy clean from duplicate data

**How we may solve this**

* Add a new column `normalized_name` or `code` to each group, category, item.
* When a new resource is either created, or updated, compute its `normalized name` or `code` (eg lowercase it, remove non alphanumeric characters)
* Include the normalized name into the changeset.

**Additional context**

**Comment by theodowling** [comment]
I would like to help with this as part of Hacktoberfest. I am going to add `normalized_name` to these three resources: `group, category, item` and it will automatically be added to the changeset when the resources are created/updated.

**Comment by pedro-gutierrez** [comment]
This is awesome, thank you so much! Please feel free to raise a PR and I'll be more than happy to approve. 
PS: Apologies, just saw this, somehow I am not getting notifications when people comment on issues in this repo :(

**Comment by pedro-gutierrez** [comment]
This is now fixed
