### ISSUE TITLE
Enable Ecto Stats in Live Dashboard

### ISSUE THREAD

**Issue by pedro-gutierrez** [distributeaid/toolbox#73]
**Is your feature request related to a problem? Please describe.**

With the latest Live Dashboard, we now have extra Ecto statistics that are turned off by default.

**Describe the solution you'd like**

Turn on Ecto Stats by following this guide:

https://hexdocs.pm/phoenix_live_dashboard/ecto_stats.html

**Comment by gkpacker** [comment]
Hey, I'd like to work on it!

**Comment by pedro-gutierrez** [comment]
Hello, thank you so much for your help! Please let me know if you need help or if you need me to review/approve.

**Comment by gkpacker** [comment]
@pedro-gutierrez I've linked the PR to the issue. Couldn't require your review directly on it and the tests doesn't appear to be running too. Please, take a look: #77

**Comment by gkpacker** [comment]
I'd like to know if it can be labeled `hacktoberfest-accepted` as well, but it's ok if not.

> Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by pedro-gutierrez** [comment]
The checks are not running, will close and re-open, and hopefully that should trigger the tests.

**Comment by pedro-gutierrez** [comment]
I was meant to do that on the PR :)
